import { Router } from "express";
import { adminAccountsRouter } from "./accounts.js";
import { adminCategoriesRouter } from "./categories.js";
import { adminContentRouter } from "./content.js";
import { adminCustomersRouter } from "./customers.js";
import { adminDashboardRouter } from "./dashboard.js";
import { adminDiscountsRouter } from "./discounts.js";
import { adminEnquiriesRouter } from "./enquiries.js";
import { adminJobsRouter } from "./jobs.js";
import { adminKitsRouter } from "./kits.js";
import { adminNotificationsRouter } from "./notifications.js";
import { adminOrdersRouter } from "./orders.js";
import { adminInvoicesRouter, adminPaymentsRouter } from "./payments.js";
import { adminProductsRouter } from "./products.js";
import { adminQuotesRouter } from "./quotes.js";
import { adminReportsRouter } from "./reports.js";
import { adminRepairsRouter } from "./repairs.js";
import { adminReviewsRouter } from "./reviews.js";
import { adminSettingsRouter } from "./settings.js";
import { adminStaffRouter } from "./staff.js";
import { adminSuppliersRouter } from "./suppliers.js";
import { adminSurveysRouter } from "./surveys.js";
import { adminZonesRouter } from "./zones.js";

export const adminRouter = Router();

adminRouter.use("/dashboard", adminDashboardRouter);
adminRouter.use("/reports", adminReportsRouter);
adminRouter.use("/orders", adminOrdersRouter);
adminRouter.use("/quotes", adminQuotesRouter);
adminRouter.use("/payments", adminPaymentsRouter);
adminRouter.use("/invoices", adminInvoicesRouter);
adminRouter.use("/customers", adminCustomersRouter);
adminRouter.use("/jobs", adminJobsRouter);
adminRouter.use("/repairs", adminRepairsRouter);
adminRouter.use("/surveys", adminSurveysRouter);
adminRouter.use("/suppliers", adminSuppliersRouter);
adminRouter.use("/products", adminProductsRouter);
adminRouter.use("/categories", adminCategoriesRouter);
adminRouter.use("/kits", adminKitsRouter);
adminRouter.use("/discounts", adminDiscountsRouter);
adminRouter.use("/content", adminContentRouter);
adminRouter.use("/reviews", adminReviewsRouter);
adminRouter.use("/zones", adminZonesRouter);
adminRouter.use("/notifications", adminNotificationsRouter);
adminRouter.use("/accounts", adminAccountsRouter);
adminRouter.use("/enquiries", adminEnquiriesRouter);
adminRouter.use("/staff", adminStaffRouter);
adminRouter.use("/settings", adminSettingsRouter);
